version: '3.1'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todos
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  postgres_data:
    driver: local
  redis-data:
    driver: local

